import { useEffect, useState } from 'react'
import { BadgeCheck, UserRound } from 'lucide-react'
import { PageHeader } from '@/components/ui/PageHeader'
import { Input } from '@/components/ui/Input'
import { Button } from '@/components/ui/Button'
import { useAuth } from '@/features/auth/AuthContext'
import { http } from '@/lib/api/http'
import { ENDPOINTS } from '@/lib/api/endpoints'
import type { ApiProfileBundle } from '@/lib/api/helpwork.types'

export default function RequesterProfilePage() {
  const { usuario } = useAuth(); const [profile, setProfile] = useState<ApiProfileBundle | null>(null); const [city, setCity] = useState(''); const [program, setProgram] = useState(''); const [level, setLevel] = useState('grado'); const [languages, setLanguages] = useState('es'); const [message, setMessage] = useState('')
  const cargar = async () => { const data = await http.get<ApiProfileBundle>(ENDPOINTS.usuarios.perfilPropio); setProfile(data); setCity(data.perfilSolicitante?.city ?? ''); setProgram(data.perfilSolicitante?.academic_program ?? ''); setLevel(data.perfilSolicitante?.academic_level ?? 'grado'); setLanguages((data.perfilSolicitante?.preferred_languages ?? ['es']).join(', ')) }
  useEffect(() => { cargar().catch(() => setMessage('No se pudo cargar tu perfil.')) }, [])
  const guardar = async () => { if (!usuario) return; await http.put(ENDPOINTS.usuarios.perfilSolicitante(usuario.id), { city, academic_program: program, academic_level: level, preferred_languages: languages.split(',').map(x => x.trim()).filter(Boolean) }); setMessage('Perfil público actualizado.'); cargar().catch(() => undefined) }
  const extra = profile?.perfilSolicitante as { average_rating?: number; review_count?: number } | undefined; const rating = Number(extra?.average_rating ?? 0); const count = Number(extra?.review_count ?? 0)
  return <div className="mx-auto max-w-3xl space-y-5"><PageHeader titulo="Perfil público" descripcion="Esta información ayuda a los HelpWorkers a entender tu necesidad y tu trayectoria." /><section className="panel overflow-hidden"><div className="h-24 bg-gradient-to-r from-brand-400 via-brand-500 to-violet-400" /><div className="flex gap-4 px-6 pb-6"><div className="-mt-10 grid h-20 w-20 place-items-center overflow-hidden rounded-full bg-brand-50 text-brand-600 ring-4 ring-white">{usuario?.avatarUrl ? <img src={usuario.avatarUrl} className="h-full w-full object-cover" alt="" /> : <UserRound size={31} />}</div><div className="pt-3"><h2 className="flex items-center gap-1.5 text-[21px] font-extrabold">{usuario?.nombre}<BadgeCheck size={18} className="text-brand-500" /></h2><p className="text-[13px] texto-suave">HelpSeeker · {program || 'Programa por definir'}</p><p className="mt-1 text-[12px] text-ink-muted">★ {rating.toFixed(1)} · {count} reseñas</p></div></div></section><section className="panel grid gap-4 p-5 sm:grid-cols-2"><Input label="Ciudad" value={city} onChange={e => setCity(e.target.value)} /><Input label="Programa académico" value={program} onChange={e => setProgram(e.target.value)} /><label><span className="mb-1.5 block text-sm font-medium text-ink-soft">Nivel académico</span><select value={level} onChange={e => setLevel(e.target.value)} className="h-12 w-full rounded-xl border border-white/80 bg-white/70 px-3"><option value="grado">Grado</option><option value="posgrado">Posgrado</option><option value="bachillerato">Bachillerato</option></select></label><Input label="Idiomas (separados por coma)" value={languages} onChange={e => setLanguages(e.target.value)} /><div className="sm:col-span-2"><Button onClick={() => guardar().catch(cause => setMessage(cause instanceof Error ? cause.message : 'No se pudo guardar.'))}>Guardar cambios</Button>{message && <p className="mt-3 text-[13px] text-brand-600">{message}</p>}</div></section></div>
}
