import { lazy, Suspense } from 'react'
import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import { PublicLayout } from '@/components/layout/PublicLayout'
import { ScrollToTop } from './ScrollToTop'
import { RutaPrivada } from './RutaPrivada'
import { RutaRol } from './RutaRol'
import { ROUTES } from '@/config/site.config'

const Home = lazy(() => import('@/features/marketing/pages/HomePage')); const Pricing = lazy(() => import('@/features/marketing/pages/PricingPage')); const Login = lazy(() => import('@/features/auth/pages/LoginPage')); const Register = lazy(() => import('@/features/auth/pages/RegisterPage')); const Role = lazy(() => import('@/features/auth/pages/RoleSelectPage')); const Callback = lazy(() => import('@/features/auth/pages/AuthCallbackPage'))
const SolicitanteLayout = lazy(() => import('@/features/solicitante/layout/SolicitanteLayout')); const ProveedorLayout = lazy(() => import('@/features/proveedor/layout/ProveedorLayout')); const AdministradorLayout = lazy(() => import('@/features/administrador/layout/AdministradorLayout'))
const SeekerHome = lazy(() => import('@/features/dashboard/pages/SeekerHomePage')); const Requests = lazy(() => import('@/features/dashboard/pages/RequestsPage')); const NewRequest = lazy(() => import('@/features/dashboard/pages/NewRequestPage')); const Matching = lazy(() => import('@/features/dashboard/pages/MatchingPage')); const Calendar = lazy(() => import('@/features/dashboard/pages/CalendarPage')); const Reviews = lazy(() => import('@/features/dashboard/pages/ReviewsPage')); const RequesterProfile = lazy(() => import('@/features/dashboard/pages/RequesterProfilePage')); const Proposals = lazy(() => import('@/features/dashboard/pages/ProposalsPage')); const Favorites = lazy(() => import('@/features/dashboard/pages/FavoritesPage')); const Notifications = lazy(() => import('@/features/dashboard/pages/NotificationsPage')); const Settings = lazy(() => import('@/features/dashboard/pages/SettingsPage')); const Help = lazy(() => import('@/features/dashboard/pages/HelpPage')); const Inbox = lazy(() => import('@/features/messages/InboxPage')); const Payments = lazy(() => import('@/features/dashboard/pages/PaymentsPage'))
const WorkerHome = lazy(() => import('@/features/dashboard/pages/WorkerHomePage')); const WorkerMatching = lazy(() => import('@/features/dashboard/pages/WorkerMatchingPage')); const Opportunities = lazy(() => import('@/features/dashboard/pages/OpportunitiesPage')); const Jobs = lazy(() => import('@/features/dashboard/pages/JobsPage')); const WorkerProfile = lazy(() => import('@/features/dashboard/pages/ProfilePage')); const ProviderRequests = lazy(() => import('@/features/proveedor/solicitante/ProveedorSolicitudesPage')); const ProviderNewRequest = lazy(() => import('@/features/proveedor/solicitante/ProveedorNuevaSolicitudPage')); const ProviderMatching = lazy(() => import('@/features/proveedor/solicitante/ProveedorMatchingSolicitudesPage'))
const loader = <div className="grid min-h-[60vh] place-items-center"><div className="h-10 w-10 animate-spin rounded-full border-4 border-brand-100 border-t-brand-500" /></div>
const privateRole = (role: 'solicitante' | 'helpworker' | 'administrador', layout: React.ReactNode) => <RutaPrivada><RutaRol rol={role}>{layout}</RutaRol></RutaPrivada>
const router = createBrowserRouter([
  { element: <><ScrollToTop /><PublicLayout /></>, children: [{ path: ROUTES.home, element: <Home /> }, { path: ROUTES.precios, element: <Pricing /> }, { path: ROUTES.login, element: <Login /> }, { path: ROUTES.registro, element: <Register /> }, { path: ROUTES.registroRol, element: <Role /> }, { path: ROUTES.authCallback, element: <Callback /> }] },
  { element: privateRole('solicitante', <SolicitanteLayout />), children: [{ path: ROUTES.appSolicitante, element: <SeekerHome /> }, { path: ROUTES.solicitudes, element: <Requests /> }, { path: ROUTES.nuevaSolicitud, element: <NewRequest /> }, { path: ROUTES.matching, element: <Matching /> }, { path: ROUTES.calendarioSolicitante, element: <Calendar /> }, { path: ROUTES.resenasSolicitante, element: <Reviews modo="solicitante" /> }, { path: ROUTES.perfilSolicitante, element: <RequesterProfile /> }, { path: ROUTES.propuestas, element: <Proposals /> }, { path: ROUTES.favoritos, element: <Favorites /> }, { path: ROUTES.notificacionesSolicitante, element: <Notifications /> }, { path: ROUTES.ajustesSolicitante, element: <Settings /> }, { path: ROUTES.ayudaSolicitante, element: <Help /> }, { path: ROUTES.mensajesSolicitante, element: <Inbox /> }, { path: ROUTES.pagos, element: <Payments /> }] },
  { element: privateRole('helpworker', <ProveedorLayout />), children: [{ path: ROUTES.appHelpWorker, element: <WorkerHome /> }, { path: ROUTES.matchingHW, element: <WorkerMatching /> }, { path: ROUTES.oportunidades, element: <Opportunities /> }, { path: ROUTES.trabajos, element: <Jobs /> }, { path: ROUTES.calendario, element: <Calendar /> }, { path: ROUTES.resenas, element: <Reviews /> }, { path: ROUTES.perfil, element: <WorkerProfile /> }, { path: ROUTES.ganancias, element: <Payments modo="helpworker" /> }, { path: ROUTES.mensajes, element: <Inbox /> }, { path: ROUTES.notificaciones, element: <Notifications /> }, { path: ROUTES.ajustes, element: <Settings /> }, { path: ROUTES.ayuda, element: <Help /> }, { path: ROUTES.proveedorSolicitudes, element: <ProviderRequests /> }, { path: ROUTES.proveedorNuevaSolicitud, element: <ProviderNewRequest /> }, { path: ROUTES.proveedorMatchingSolicitudes, element: <ProviderMatching /> }, { path: ROUTES.proveedorPropuestas, element: <Proposals /> }, { path: ROUTES.proveedorFavoritos, element: <Favorites /> }] },
  { element: privateRole('administrador', <AdministradorLayout />), children: [{ path: ROUTES.appAdministrador, element: <div className="panel p-6"><h1 className="text-xl font-bold">Panel administrativo</h1><p className="mt-2 texto-suave">Estructura de rutas y sidebar preparada. Los módulos administrativos se conectarán después.</p></div> }] },
  { path: '*', element: <div className="grid min-h-screen place-items-center text-ink-muted">404 — Página no encontrada</div> },
])
export function AppRouter() { return <Suspense fallback={loader}><RouterProvider router={router} /></Suspense> }
