import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { Bell, Briefcase, Calendar, FileText, Heart, HelpCircle, Home, Inbox, MessageSquare, Settings, Sparkles, Star, User, Wallet, type LucideIcon } from 'lucide-react'
import { Logo } from '@/components/layout/Logo'
import { UserMenu } from '@/components/layout/UserMenu'
import { useAuth } from '@/features/auth/AuthContext'
import { ROUTES } from '@/config/site.config'
import { cn } from '@/lib/cn'
import { AppBar } from '@/components/layout/AppBar'
const provider = [{ l: 'Inicio', to: ROUTES.appHelpWorker, i: Home }, { l: 'Matching', to: ROUTES.matchingHW, i: Sparkles }, { l: 'Oportunidades', to: ROUTES.oportunidades, i: Briefcase }, { l: 'Mis trabajos', to: ROUTES.trabajos, i: FileText }, { l: 'Calendario', to: ROUTES.calendario, i: Calendar }, { l: 'Ganancias', to: ROUTES.ganancias, i: Wallet }, { l: 'Reseñas', to: ROUTES.resenas, i: Star }, { l: 'Perfil público', to: ROUTES.perfil, i: User }, { l: 'Mensajes', to: ROUTES.mensajes, i: MessageSquare }, { l: 'Notificaciones', to: ROUTES.notificaciones, i: Bell }, { l: 'Ajustes', to: ROUTES.ajustes, i: Settings }, { l: 'Ayuda', to: ROUTES.ayuda, i: HelpCircle }]
const requester = [{ l: 'Mis solicitudes', to: ROUTES.proveedorSolicitudes, i: FileText }, { l: 'Propuestas', to: ROUTES.proveedorPropuestas, i: Inbox }, { l: 'Favoritos', to: ROUTES.proveedorFavoritos, i: Heart }]
type SidebarItem = { l: string; to: string; i: LucideIcon }
/** Sidebar exclusivo del proveedor. Su doble rol nunca usa rutas /app/solicitante. */
export default function ProveedorLayout() { const { pathname } = useLocation(); const { usuario } = useAuth(); const dual = usuario?.roles.includes('solicitante') ?? false; const render = (items: SidebarItem[], disabled = false) => items.map(({ l, to, i: Icon }) => disabled ? <div key={l} className="flex cursor-not-allowed items-center gap-3 rounded-xl px-3.5 py-2.5 text-[14px] text-ink-muted/45"><Icon size={18} />{l}<small className="ml-auto">Bloqueado</small></div> : <NavLink key={to} to={to} className={cn('flex items-center gap-3 rounded-xl px-3.5 py-2.5 text-[14.5px] font-medium', pathname === to ? 'bg-brand-50 text-brand-700' : 'text-ink-soft hover:bg-brand-50/70')}><Icon size={18} />{l}</NavLink>); return <div className="ambiente min-h-screen"><aside className="fixed inset-y-0 left-0 hidden w-[264px] flex-col border-r border-white/70 bg-white/75 backdrop-blur-2xl lg:flex"><div className="px-5 py-6"><Logo /></div><nav className="flex-1 space-y-1 overflow-y-auto px-3">{render(provider)}<p className="px-3 pt-4 text-[10px] font-bold uppercase tracking-wider text-ink-muted">Modo HelpSeeker</p>{render(requester, !dual)}</nav><div className="border-t border-surface-line p-2"><UserMenu nombre={usuario?.nombre ?? 'HelpWorker'} subtitulo={dual ? 'HelpWorker · HelpSeeker' : 'HelpWorker'} avatarUrl={usuario?.avatarUrl ?? ''} /></div></aside><main className="lg:pl-[264px]"><AppBar notificationsTo={ROUTES.notificaciones} /><div className="px-5 py-7 sm:px-8"><Outlet /></div></main></div> }
